services:
  - type: web
    name: Post OCR tool
    env: node
    plan: standard
    # Update the following line with your Strapi GitHub repo
    repo: https://github.com/OpenPecha/pecha-tool-for-ocr-correction.git
    branch: main
    buildCommand: npm ci --production=false && npm run build && npm prune --production
    startCommand: npx prisma migrate deploy && npm run start
    envVars:
      - key: NODE_VERSION
        value: ~18.18.0
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: post-ocr-pg
          property: connectionString

databases:
  - name: post-ocr-pg
    plan: standard
